import {
    Binary,
    Braces,
    Clock,
    Code2,
    Crop,
    FileDown,
    FileImage,
    FileText,
    Globe,
    Hash,
    Image,
    Key,
    Merge,
    PenLine,
    Play,
    PlugZap,
    QrCode,
    RefreshCw,
    Send,
    Sparkles,
    Type,
    Video,
    Wrench,
} from "lucide-react";
import { FlattenedTool, ToolCategory } from "./types";

export const toolIcons: Record<string, React.ElementType> = {
  "Image Cropper": Crop,
  "Image Compressor": FileDown,
  "Format Converter": RefreshCw,
  "Background Remover": Image,
  "Image to Text (OCR)": Type,
  "Image Resizer": Image,
  "Blur Image": Image,
  "Merge PDF": Merge,
  "Compress PDF": FileDown,
  "PDF to Image": FileImage,
  "Image to PDF": FileText,
  "Split PDF": FileText,
  "Rotate PDF": RefreshCw,
  "PDF Editor": PenLine,
  "JSON Formatter": Braces,
  "Code Beautifier": Code2,
  "SQL Formatter": Code2,
  "Base64": Binary,
  "UUID Generator": Hash,
  "JWT Decoder": Key,
  "Hash Generator": Hash,
  "Regex Tester": Code2,
  "URL Encoder": Code2,
  "Cron Parser": Clock,
  "Markdown Renderer": FileText,
  "Diff Checker": Code2,
  "Online Compiler": Play,
  "Request Catcher": Globe,
  "Local Proxy": PlugZap,
  "API Client": Send,
  "WebSocket Client": PlugZap,
  "Word Counter": Hash,
  "Case Converter": Type,
  "Remove Duplicates": Type,
  "Text Formatter": Type,
  "Lorem Ipsum": Type,
  "Password Generator": Key,
  "QR Code": QrCode,
  "Barcode Generator": Hash,
  "Unit Converter": RefreshCw,
  "Color Converter": Sparkles,
  "Timestamp Converter": Clock,
  "Countdown Timer": Clock,
  "Video to Audio": Video,
  "Video Compressor": FileDown,
  "Video to GIF": Video,
};

export const toolCategories: ToolCategory[] = [
  {
    title: "Image",
    icon: Image,
    href: "/#image-tools",
    color: "text-sky-600 dark:text-sky-400",
    bgColor: "bg-sky-500/10",
    hoverBg: "hover:bg-sky-500/10",
    tools: [
      { title: "Background Remover", href: "/image-tools/remove-background", desc: "AI-powered" },
      { title: "Blur Image", href: "/image-tools/blur-image", desc: "Blur & pixelate" },
      { title: "Format Converter", href: "/image-tools/format-converter", desc: "PNG, JPG, WebP" },
      { title: "Image Compressor", href: "/image-tools/compress-image", desc: "Reduce file size" },
      { title: "Image Cropper", href: "/image-tools/crop-image", desc: "Crop with precision" },
      { title: "Image Resizer", href: "/image-tools/resize-image", desc: "Any dimension" },
      { title: "Image to Text (OCR)", href: "/image-tools/ocr", desc: "Extract text" },
    ],
  },
  {
    title: "PDF",
    icon: FileText,
    href: "/#pdf-tools",
    color: "text-rose-600 dark:text-rose-400",
    bgColor: "bg-rose-500/10",
    hoverBg: "hover:bg-rose-500/10",
    tools: [
      { title: "Compress PDF", href: "/pdf-tools/compress-pdf", desc: "Reduce size" },
      { title: "Image to PDF", href: "/pdf-tools/image-to-pdf", desc: "Create PDF" },
      { title: "Merge PDF", href: "/pdf-tools/merge-pdf", desc: "Combine files" },
      { title: "PDF Editor", href: "/pdf-tools/edit-pdf", desc: "Edit any PDF" },
      { title: "PDF to Image", href: "/pdf-tools/pdf-to-image", desc: "Convert pages" },
      { title: "Rotate PDF", href: "/pdf-tools/rotate-pdf", desc: "Rotate pages" },
      { title: "Split PDF", href: "/pdf-tools/split-pdf", desc: "Separate pages" },
    ],
  },
  {
    title: "Text",
    icon: Type,
    href: "/#text-tools",
    color: "text-emerald-600 dark:text-emerald-400",
    bgColor: "bg-emerald-500/10",
    hoverBg: "hover:bg-emerald-500/10",
    tools: [
      { title: "Case Converter", href: "/text-tools/case-converter", desc: "Change case" },
      { title: "Lorem Ipsum", href: "/text-tools/lorem-ipsum", desc: "Generate text" },
      { title: "Remove Duplicates", href: "/text-tools/remove-duplicates", desc: "Clean text" },
      { title: "Text Formatter", href: "/text-tools/text-formatter", desc: "Format text" },
      { title: "Word Counter", href: "/text-tools/word-counter", desc: "Count words" },
    ],
  },
  {
    title: "Dev",
    icon: Code2,
    href: "/#dev-tools",
    color: "text-amber-600 dark:text-amber-400",
    bgColor: "bg-amber-500/10",
    hoverBg: "hover:bg-amber-500/10",
    tools: [
      { title: "API Client", href: "/dev-tools/api-client", desc: "Send HTTP requests" },
      { title: "Base64", href: "/dev-tools/base64", desc: "Encode/decode" },
      { title: "Code Beautifier", href: "/dev-tools/code-beautifier", desc: "Format HTML/CSS/JS" },
      { title: "Cron Parser", href: "/dev-tools/cron-parser", desc: "Parse cron" },
      { title: "Diff Checker", href: "/dev-tools/diff-checker", desc: "Compare text" },
      { title: "Hash Generator", href: "/dev-tools/hash-generator", desc: "MD5, SHA" },
      { title: "JSON Formatter", href: "/dev-tools/json-formatter", desc: "Format & validate JSON" },
      { title: "JWT Decoder", href: "/dev-tools/jwt-decoder", desc: "Decode tokens" },
      { title: "Markdown Renderer", href: "/dev-tools/markdown-renderer", desc: "Render markdown" },
      { title: "Online Compiler", href: "/dev-tools/online-compiler", desc: "Run code live" },
      { title: "Regex Tester", href: "/dev-tools/regex-tester", desc: "Test patterns" },
      { title: "Request Catcher", href: "/dev-tools/request-catcher", desc: "Capture requests" },
      { title: "Local Proxy", href: "/dev-tools/local-proxy", desc: "Forward to localhost" },
      { title: "SQL Formatter", href: "/dev-tools/sql-formatter", desc: "Beautify SQL queries" },
      { title: "URL Encoder", href: "/dev-tools/url-encoder", desc: "Encode URLs" },
      { title: "UUID Generator", href: "/dev-tools/uuid-generator", desc: "Generate IDs" },
      { title: "WebSocket Client", href: "/dev-tools/websocket-client", desc: "WS connections" },
    ],
  },
  {
    title: "Video",
    icon: Video,
    href: "/#video-tools",
    color: "text-orange-600 dark:text-orange-400",
    bgColor: "bg-orange-500/10",
    hoverBg: "hover:bg-orange-500/10",
    tools: [
      { title: "Video to Audio", href: "/video-tools/video-to-audio", desc: "Extract audio" },
      { title: "Video Compressor", href: "/video-tools/compress-video", desc: "Reduce size" },
      { title: "Video to GIF", href: "/video-tools/video-to-gif", desc: "Create GIFs" },
    ],
  },
  {
    title: "Utility",
    icon: Wrench,
    href: "/#utility-tools",
    color: "text-cyan-600 dark:text-cyan-400",
    bgColor: "bg-cyan-500/10",
    hoverBg: "hover:bg-cyan-500/10",
    tools: [
      { title: "Barcode Generator", href: "/utility-tools/barcode", desc: "Generate barcodes" },
      { title: "Color Converter", href: "/utility-tools/color-converter", desc: "HEX, RGB, HSL" },
      { title: "Countdown Timer", href: "/utility-tools/countdown", desc: "Create timers" },
      { title: "Password Generator", href: "/utility-tools/password-generator", desc: "Secure passwords" },
      { title: "QR Code", href: "/utility-tools/qr-code", desc: "Create codes" },
      { title: "Timestamp Converter", href: "/utility-tools/timestamp", desc: "Unix timestamps" },
      { title: "Unit Converter", href: "/utility-tools/unit-converter", desc: "Convert units" },
    ],
  },
];

export const allTools: FlattenedTool[] = toolCategories.flatMap((cat) =>
  cat.tools.map((tool) => ({
    ...tool,
    category: cat.title,
    color: cat.color,
    bgColor: cat.bgColor
  }))
);

/** Top 10 most popular tools shown in the navbar mega menu */
export const top10Tools = [
  { title: "PDF Editor", href: "/pdf-tools/edit-pdf", desc: "Edit text, images & annotations", category: "PDF" },
  { title: "Image Compressor", href: "/image-tools/compress-image", desc: "Reduce file size without quality loss", category: "Image" },
  { title: "Online Compiler", href: "/dev-tools/online-compiler", desc: "Write & run code in 10+ languages", category: "Dev" },
  { title: "Merge PDF", href: "/pdf-tools/merge-pdf", desc: "Combine multiple PDFs into one", category: "PDF" },
  { title: "Background Remover", href: "/image-tools/remove-background", desc: "AI-powered background removal", category: "Image" },
  { title: "JSON Formatter", href: "/dev-tools/json-formatter", desc: "Format & validate JSON", category: "Dev" },
  { title: "QR Code", href: "/utility-tools/qr-code", desc: "Create QR codes instantly", category: "Utility" },
  { title: "Password Generator", href: "/utility-tools/password-generator", desc: "Generate secure passwords", category: "Utility" },
  { title: "Video to GIF", href: "/video-tools/video-to-gif", desc: "Convert video clips to GIFs", category: "Video" },
  { title: "Word Counter", href: "/text-tools/word-counter", desc: "Count words, characters & more", category: "Text" },
];
