import { catalog, catalogCategories } from "@/lib/tool-catalog";
import {
    Binary,
    Braces,
    Clock,
    Code2,
    Crop,
    FileDown,
    FileImage,
    FileText,
    Gauge,
    Globe,
    Hash,
    IdCard,
    Image,
    Key,
    Merge,
    PenLine,
    Play,
    PlugZap,
    QrCode,
    RefreshCw,
    Send,
    Sparkles,
    Target,
    Type,
    Video,
    Wrench,
} from "lucide-react";
import { FlattenedTool, ToolCategory } from "./types";

export const toolIcons: Record<string, React.ElementType> = {
  "Image Cropper": Crop,
  "Image Compressor": FileDown,
  "Compress to Size": Target,
  "Document Photo": IdCard,
  "Format Converter": RefreshCw,
  "Background Remover": Image,
  "HEIC to JPG": RefreshCw,
  "WebP to PNG": RefreshCw,
  "AVIF to JPG": RefreshCw,
  "Image to Text (OCR)": Type,
  "Image Resizer": Image,
  "Blur Image": Image,
  "Merge PDF": Merge,
  "Compress PDF": FileDown,
  "PDF to Size": Gauge,
  "PDF to Image": FileImage,
  "Image to PDF": FileText,
  "Split PDF": FileText,
  "Rotate PDF": RefreshCw,
  "PDF Editor": PenLine,
  "JSON Formatter": Braces,
  "Code Beautifier": Code2,
  "SQL Formatter": Code2,
  "Base64": Binary,
  "UUID Generator": Hash,
  "JWT Decoder": Key,
  "Hash Generator": Hash,
  "Regex Tester": Code2,
  "URL Encoder": Code2,
  "Cron Parser": Clock,
  "Markdown Renderer": FileText,
  "Diff Checker": Code2,
  "Online Compiler": Play,
  "Request Catcher": Globe,
  "Local Proxy": PlugZap,
  "API Client": Send,
  "WebSocket Client": PlugZap,
  "Word Counter": Hash,
  "Case Converter": Type,
  "Remove Duplicates": Type,
  "Text Formatter": Type,
  "Lorem Ipsum": Type,
  "Password Generator": Key,
  "QR Code": QrCode,
  "Barcode Generator": Hash,
  "Unit Converter": RefreshCw,
  "Color Converter": Sparkles,
  "Timestamp Converter": Clock,
  "Countdown Timer": Clock,
  "Video to Audio": Video,
  "Video Compressor": FileDown,
  "Video to GIF": Video,
};

const presentation = {
  Image: { icon: Image, color: "text-sky-600 dark:text-sky-400", bgColor: "bg-sky-500/10", hoverBg: "hover:bg-sky-500/10" },
  PDF: { icon: FileText, color: "text-rose-600 dark:text-rose-400", bgColor: "bg-rose-500/10", hoverBg: "hover:bg-rose-500/10" },
  Text: { icon: Type, color: "text-emerald-600 dark:text-emerald-400", bgColor: "bg-emerald-500/10", hoverBg: "hover:bg-emerald-500/10" },
  Dev: { icon: Code2, color: "text-amber-600 dark:text-amber-400", bgColor: "bg-amber-500/10", hoverBg: "hover:bg-amber-500/10" },
  Video: { icon: Video, color: "text-orange-600 dark:text-orange-400", bgColor: "bg-orange-500/10", hoverBg: "hover:bg-orange-500/10" },
  Utility: { icon: Wrench, color: "text-cyan-600 dark:text-cyan-400", bgColor: "bg-cyan-500/10", hoverBg: "hover:bg-cyan-500/10" },
};
export const toolCategories: ToolCategory[] = catalogCategories.map(group => ({
  ...group, ...presentation[group.title], tools: catalog.filter(tool => tool.category === group.title),
}));
export const allTools: FlattenedTool[] = catalog.map(tool => ({ ...tool, ...presentation[tool.category as keyof typeof presentation] }));
/** Editorially selected from the catalog, never a measured popularity claim. */
export const top10Tools = allTools.filter(tool => tool.featuredWeight > 0).sort((a,b) => b.featuredWeight - a.featuredWeight);
